export const flashcards = [
{ id: 1, description: "חרטום של מפרשית", image: "/images/image1.gif" },
{ id: 2, description: "חרטום של כלי שיט מוגבל בשל השוקע מעל 50 מטר", image: "/images/image2.gif" },
{ id: 3, description: "ירכתיים של מוגבל בשל עבודתו, דופן שמאל פנויה למעבר", image: "/images/image3.gif" },
{ id: 4, description: "ירכתיים של דייג עם רשת מעל 150 מטר בצד ימין", image: "/images/image4.gif" },
{ id: 5, description: "חרטום של ממוכן מעל 50 מטר", image: "/images/image5.gif" },
{ id: 6, description: "דופן שמאל של גורר משך מתחת ל- 200 מטר ואורך מתחת למטרים-50", image: "/images/image6.gif" },
{ id: 7, description: "על שרטון עד 50 מטר", image: "/images/image7.gif" },
{ id: 8, description: "חרטום של דייג", image: "/images/image8.gif" },
{ id: 9, description: "חרטום של שולה מוקשים קטן מ- 50 מטר", image: "/images/image9.gif" },
{ id: 10, description: "חרטום של נתב", image: "/images/image10.gif" },
{ id: 11, description: "דופן שמאל של גורר משך מתחת ל-200 מטר ואורכו מעל 50 מטר מוגבל בכושרו לתמרן ונגרר", image: "/images/image11.gif" },
{ id: 12, description: "דופן שמאל של ממוכן מעל 50 מטר", image: "/images/image12.gif" },
{ id: 13, description: "דופן שמאל של מפרשית", image: "/images/image13.gif" },
{ id: 14, description: "דופן ימין של מפרשית עם אורות רשות", image: "/images/image14.gif" },
{ id: 15, description: "חרטום של ממוכן עד 50 מטר", image: "/images/image15.gif" },
{ id: 16, description: "חרטום של רחפת עד 50 מטר", image: "/images/image16.gif" },
{ id: 17, description: "ירכתיים של גורר ונגרר", image: "/images/image17.gif" },
{ id: 18, description: "ירכתיים של רחפת (האור העליון הוא שגיאה של משרד התחבורה)", image: "/images/image18.gif" },
{ id: 19, description: "דופן ימין של מכמורתן מעל 50 מטר", image: "/images/image19.gif" },
{ id: 20, description: "ירכתיים של כלי שייט ללא שליטה", image: "/images/image20.gif" },
{ id: 21, description: "ירכתיים של נתב", image: "/images/image21.gif" },
{ id: 22, description: "דופן שמאל של מוגבל בשל עבודתו מעל 50 מטר", image: "/images/image22.gif" },
{ id: 23, description: "ירכתיים של גורר המוגבל בכושרו לתמרן ונגרר", image: "/images/image23.gif" },
{ id: 24, description: "דופן שמאל של מפרשית עם אורות רשות", image: "/images/image24.gif" },
{ id: 25, description: "דופן ימין של מוגבל בשל השוקע מעל 50 מטר", image: "/images/image25.gif" },
{ id: 26, description: "מוגבל בשל עבודתו, בדרך ואינו עושה דרכו. צד מעבר מימין ומכשול מצד שמאל.", image: "/images/image26.gif" },
{ id: 27, description: "ירכתיים של מפרשית/ ירכתיים של ממוכן/ כלי שייט עד 7 מ' ומתחת ל6 כוח סוס/ עוגן עד 50 מטר", image: "/images/image27.gif" },
{ id: 28, description: "חרטום של גורר משך מעל 200 ואורכו מתחת ל-50 מטר אורך או חרטום של גורר משך מתחת ל-200 מטר ואורכו מעל 50 מטר", image: "/images/image28.gif" },
{ id: 29, description: "ירכתיים של מכמורתן (שני אורות לבנים מבטאים הורדת ציוד דייג למים – לא לבחינה).", image: "/images/image29.gif" },
{ id: 30, description: "דופן שמאל של ממכון עד 50 מטר", image: "/images/image30.gif" },
{ id: 31, description: "דופן ימין של שולה מוקשים עד 50 מטר", image: "/images/image31.gif" },
{ id: 32, description: "ירכתיים של שולה מוקשים", image: "/images/image32.gif" },
{ id: 33, description: "דופן שמאל של כלי שייט ללא שליטה", image: "/images/image33.gif" },
{ id: 34, description: "דופן ימין של נתב", image: "/images/image34.gif" },
{ id: 35, description: "חרטום של מוגבל עד 50 מטר", image: "/images/image35.gif" },
{ id: 36, description: "חרטום של ממוכן מעל 50 מטר או חרטום של גורר בעל משך קטן מ- 200 מטר ואורכו מתחת ל-50 מטר", image: "/images/image36.gif" },
{ id: 37, description: "ירכתיים של מפרשית עם אורות רשות", image: "/images/image37.gif" },
{ id: 38, description: "ירכתיים של מוגבל בשל השוקע", image: "/images/image38.gif" },
{ id: 39, description: "על שרטון מעל 50 מטר דופן ימין", image: "/images/image39.gif" },
{ id: 40, description: "דופן ימין של רחפת קטנה מ- 50 מטר", image: "/images/image40.gif" },
{ id: 41, description: "דופן ימין של ממוכן מעל 50 מטר", image: "/images/image41.gif" },
{ id: 42, description: "ירכתיים של מוגבל בשל עבודתו", image: "/images/image42.gif" },
{ id: 43, description: "דופן ימין של ממוכן עד 50 מטר", image: "/images/image43.gif" },
{ id: 44, description: "דופן שמאל של מכמורתן מעל 50 מטר", image: "/images/image44.gif" },
{ id: 45, description: "דופן ימין של ללא שליטה", image: "/images/image45.gif" },
{ id: 46, description: "דופן שמאל של נתב", image: "/images/image46.gif" },
{ id: 47, description: "חרטום של גורר בעל משך מעל 200 ואורכו מעל ל-50 מטר המוגבל בכושרו לתמרן", image: "/images/image47.gif" },
{ id: 48, description: "דופן ימין של מפרשית", image: "/images/image48.gif" },
{ id: 49, description: "דופן שמאל של מוגבל בשל השוקע מעל 50 מטרים", image: "/images/image49.gif" },
{ id: 50, description: "חרטום של מוגבל בשל עבודתו עד 50 מטר כאשר דופן שמאל פנויה למעבר", image: "/images/image50.gif" },
{ id: 51, description: "דופן ימין של דייג מתחת ל- מטרים50", image: "/images/image51.gif" },
{ id: 52, description: "דופן שמאל של ממוכן מעל 50 מטר", image: "/images/image52.gif" },
{ id: 53, description: "דופן ימין של גורר בעל משך מתחת ל- 200 מטר ואורכו מעל 50 מטר ונגרר", image: "/images/image53.gif" },
{ id: 54, description: "דופן ימין של מוגבל בשל עבודתו עד 50 מטר עם ציון סכנת מעבר בצדו הימני", image: "/images/image54.gif" },
{ id: 55, description: "דופן שמאל של דייג", image: "/images/image55.gif" },
{ id: 56, description: "דופן שמאל של שולה מוקשים עד 50 מטרים", image: "/images/image56.gif" },
{ id: 57, description: "ללא שליטה שיש עליו נתב (שגיאה של משרד התחבורה)", image: "/images/image57.gif" },
{ id: 58, description: "חרטום של מפרשית עם אורות רשות", image: "/images/image58.gif" },
{ id: 59, description: "דופן ימין של גורר בעל משך מתחת ל- 200 מטר, אורכו מעל 50 מטר, המוגבל בכושרו לתמרן ונגרר", image: "/images/image59.gif" },
{ id: 60, description: "דופן שמאל של גורר בעל משך מעל 200 מטר, אורכו מעל 50 מטר ונגרר", image: "/images/image60.gif" },
{ id: 61, description: "דופן ימין של עוגן מעל 50 מטר", image: "/images/image61.gif" },
{ id: 62, description: "דופן שמאל של רחפת הקטנה מ- מטרים50", image: "/images/image62.gif" },
{ id: 63, description: "חרטום של גורר בעל משך קטן מ- 200 מטר ואורכו קטן מ-50 מטר הגורר נגרר בגרירת דופן", image: "/images/image63.gif" },
{ id: 64, description: "חרטום של מכמורתן עד 50 מטר", image: "/images/image64.gif" },
{ id: 65, description: "דופן שמאל של מוגבל בשל עבודתו עד 50 מטר עם ציון מעבר בטוח בצדו השמאלי", image: "/images/image65.gif" },
{ id: 66, description: "חרטום של כלי שייט ללא שליטה", image: "/images/image66.gif" },
{ id: 67, description: "דופן ימין של מוגבל בשל עבודתו מעל 50 מטר", image: "/images/image67.gif" },
{ id: 68, description: "חרטום של שולת מוקשים מתחת ל-50 מטר (חסר אור בתמונה של משרד התחבורה)", image: "/images/image68.gif" },
{ id: 69, description: "דופן ימין של ממוכן מעל 50 מטר", image: "/images/image69.gif" },
{ id: 70, description: "כלי שייט המבצע עבודת צלילה - יש להתרחק מטר200", image: "/images/image70.gif" },
{ id: 71, description: "כניסה למרינה באזור -IALAA", image: "/images/image71.gif" },
{ id: 72, description: "דופן ימין של גורר בעל משך מעל 200 מטר וארכו מעל 50 מטרים ונגרר", image: "/images/image72.gif" },
{ id: 73, description: "מכמורתן בדרך ואינו עושה דרכו", image: "/images/image73.gif" },
{ id: 74, description: "כניסה למרינה באזור -IALAB", image: "/images/image74.gif" },
];
