export const flashcards = [
{ id: 1, description: "חרטום של מפרשית", image: "/images/image1.gif", type: "Lights" },
{ id: 2, description: "חרטום של כלי שיט מוגבל בשל השוקע מעל 50 מטר", image: "/images/image2.gif", type: "Lights" },
{ id: 3, description: "ירכתיים של מוגבל בשל עבודתו, דופן שמאל פנויה למעבר", image: "/images/image3.gif", type: "Lights" },
{ id: 4, description: "ירכתיים של דייג עם רשת מעל 150 מטר בצד ימין", image: "/images/image4.gif", type: "Lights" },
{ id: 5, description: "חרטום של ממוכן מעל 50 מטר", image: "/images/image5.gif", type: "Lights" },
{ id: 6, description: "דופן שמאל של גורר משך מתחת ל- 200 מטר ואורך מתחת למטרים-50", image: "/images/image6.gif", type: "Lights" },
{ id: 7, description: "על שרטון עד 50 מטר", image: "/images/image7.gif", type: "Lights" },
{ id: 8, description: "חרטום של דייג", image: "/images/image8.gif", type: "Lights" },
{ id: 9, description: "חרטום של שולה מוקשים קטן מ- 50 מטר", image: "/images/image9.gif", type: "Lights" },
{ id: 10, description: "חרטום של נתב", image: "/images/image10.gif", type: "Lights" },
{ id: 11, description: "דופן שמאל של גורר משך מתחת ל-200 מטר ואורכו מעל 50 מטר מוגבל בכושרו לתמרן ונגרר", image: "/images/image11.gif", type: "Lights" },
{ id: 12, description: "דופן שמאל של ממוכן מעל 50 מטר", image: "/images/image12.gif", type: "Lights" },
{ id: 13, description: "דופן שמאל של מפרשית", image: "/images/image13.gif", type: "Lights" },
{ id: 14, description: "דופן ימין של מפרשית עם אורות רשות", image: "/images/image14.gif", type: "Lights" },
{ id: 15, description: "חרטום של ממוכן עד 50 מטר", image: "/images/image15.gif", type: "Lights" },
{ id: 16, description: "חרטום של רחפת עד 50 מטר", image: "/images/image16.gif", type: "Lights" },
{ id: 17, description: "ירכתיים של גורר ונגרר", image: "/images/image17.gif", type: "Lights" },
{ id: 18, description: "ירכתיים של רחפת (האור העליון הוא שגיאה של משרד התחבורה)", image: "/images/image18.gif", type: "Lights" },
{ id: 19, description: "דופן ימין של מכמורתן מעל 50 מטר", image: "/images/image19.gif", type: "Lights" },
{ id: 20, description: "ירכתיים של כלי שייט ללא שליטה", image: "/images/image20.gif", type: "Lights" },
{ id: 21, description: "ירכתיים של נתב", image: "/images/image21.gif", type: "Lights" },
{ id: 22, description: "דופן שמאל של מוגבל בשל עבודתו מעל 50 מטר", image: "/images/image22.gif", type: "Lights" },
{ id: 23, description: "ירכתיים של גורר המוגבל בכושרו לתמרן ונגרר", image: "/images/image23.gif", type: "Lights" },
{ id: 24, description: "דופן שמאל של מפרשית עם אורות רשות", image: "/images/image24.gif", type: "Lights" },
{ id: 25, description: "דופן ימין של מוגבל בשל השוקע מעל 50 מטר", image: "/images/image25.gif", type: "Lights" },
{ id: 26, description: "מוגבל בשל עבודתו, בדרך ואינו עושה דרכו. צד מעבר מימין ומכשול מצד שמאל.", image: "/images/image26.gif", type: "Lights" },
{ id: 27, description: "ירכתיים של מפרשית/ ירכתיים של ממוכן/ כלי שייט עד 7 מ' ומתחת ל6 כוח סוס/ עוגן עד 50 מטר", image: "/images/image27.gif", type: "Lights" },
{ id: 28, description: "חרטום של גורר משך מעל 200 ואורכו מתחת ל-50 מטר אורך או חרטום של גורר משך מתחת ל-200 מטר ואורכו מעל 50 מטר", image: "/images/image28.gif", type: "Lights" },
{ id: 29, description: "ירכתיים של מכמורתן (שני אורות לבנים מבטאים הורדת ציוד דייג למים – לא לבחינה).", image: "/images/image29.gif", type: "Lights" },
{ id: 30, description: "דופן שמאל של ממכון עד 50 מטר", image: "/images/image30.gif", type: "Lights" },
{ id: 31, description: "דופן ימין של שולה מוקשים עד 50 מטר", image: "/images/image31.gif", type: "Lights" },
{ id: 32, description: "ירכתיים של שולה מוקשים", image: "/images/image32.gif", type: "Lights" },
{ id: 33, description: "דופן שמאל של כלי שייט ללא שליטה", image: "/images/image33.gif", type: "Lights" },
{ id: 34, description: "דופן ימין של נתב", image: "/images/image34.gif", type: "Lights" },
{ id: 35, description: "חרטום של מוגבל עד 50 מטר", image: "/images/image35.gif", type: "Lights" },
{ id: 36, description: "חרטום של ממוכן מעל 50 מטר או חרטום של גורר בעל משך קטן מ- 200 מטר ואורכו מתחת ל-50 מטר", image: "/images/image36.gif", type: "Lights" },
{ id: 37, description: "ירכתיים של מפרשית עם אורות רשות", image: "/images/image37.gif", type: "Lights" },
{ id: 38, description: "ירכתיים של מוגבל בשל השוקע", image: "/images/image38.gif", type: "Lights" },
{ id: 39, description: "על שרטון מעל 50 מטר דופן ימין", image: "/images/image39.gif", type: "Lights" },
{ id: 40, description: "דופן ימין של רחפת קטנה מ- 50 מטר", image: "/images/image40.gif", type: "Lights" },
{ id: 41, description: "דופן ימין של ממוכן מעל 50 מטר", image: "/images/image41.gif", type: "Lights" },
{ id: 42, description: "ירכתיים של מוגבל בשל עבודתו", image: "/images/image42.gif", type: "Lights" },
{ id: 43, description: "דופן ימין של ממוכן עד 50 מטר", image: "/images/image43.gif", type: "Lights" },
{ id: 44, description: "דופן שמאל של מכמורתן מעל 50 מטר", image: "/images/image44.gif", type: "Lights" },
{ id: 45, description: "דופן ימין של ללא שליטה", image: "/images/image45.gif", type: "Lights" },
{ id: 46, description: "דופן שמאל של נתב", image: "/images/image46.gif", type: "Lights" },
{ id: 47, description: "חרטום של גורר בעל משך מעל 200 ואורכו מעל ל-50 מטר המוגבל בכושרו לתמרן", image: "/images/image47.gif", type: "Lights" },
{ id: 48, description: "דופן ימין של מפרשית", image: "/images/image48.gif", type: "Lights" },
{ id: 49, description: "דופן שמאל של מוגבל בשל השוקע מעל 50 מטרים", image: "/images/image49.gif", type: "Lights" },
{ id: 50, description: "חרטום של מוגבל בשל עבודתו עד 50 מטר כאשר דופן שמאל פנויה למעבר", image: "/images/image50.gif", type: "Lights" },
{ id: 51, description: "דופן ימין של דייג מתחת ל- מטרים50", image: "/images/image51.gif", type: "Lights" },
{ id: 52, description: "דופן שמאל של ממוכן מעל 50 מטר", image: "/images/image52.gif", type: "Lights" },
{ id: 53, description: "דופן ימין של גורר בעל משך מתחת ל- 200 מטר ואורכו מעל 50 מטר ונגרר", image: "/images/image53.gif", type: "Lights" },
{ id: 54, description: "דופן ימין של מוגבל בשל עבודתו עד 50 מטר עם ציון סכנת מעבר בצדו הימני", image: "/images/image54.gif", type: "Lights" },
{ id: 55, description: "דופן שמאל של דייג", image: "/images/image55.gif", type: "Lights" },
{ id: 56, description: "דופן שמאל של שולה מוקשים עד 50 מטרים", image: "/images/image56.gif", type: "Lights" },
{ id: 57, description: "ללא שליטה שיש עליו נתב (שגיאה של משרד התחבורה)", image: "/images/image57.gif", type: "Lights" },
{ id: 58, description: "חרטום של מפרשית עם אורות רשות", image: "/images/image58.gif", type: "Lights" },
{ id: 59, description: "דופן ימין של גורר בעל משך מתחת ל- 200 מטר, אורכו מעל 50 מטר, המוגבל בכושרו לתמרן ונגרר", image: "/images/image59.gif", type: "Lights" },
{ id: 60, description: "דופן שמאל של גורר בעל משך מעל 200 מטר, אורכו מעל 50 מטר ונגרר", image: "/images/image60.gif", type: "Lights" },
{ id: 61, description: "דופן ימין של עוגן מעל 50 מטר", image: "/images/image61.gif", type: "Lights" },
{ id: 62, description: "דופן שמאל של רחפת הקטנה מ- מטרים50", image: "/images/image62.gif", type: "Lights" },
{ id: 63, description: "חרטום של גורר בעל משך קטן מ- 200 מטר ואורכו קטן מ-50 מטר הגורר נגרר בגרירת דופן", image: "/images/image63.gif", type: "Lights" },
{ id: 64, description: "חרטום של מכמורתן עד 50 מטר", image: "/images/image64.gif", type: "Lights" },
{ id: 65, description: "דופן שמאל של מוגבל בשל עבודתו עד 50 מטר עם ציון מעבר בטוח בצדו השמאלי", image: "/images/image65.gif", type: "Lights" },
{ id: 66, description: "חרטום של כלי שייט ללא שליטה", image: "/images/image66.gif", type: "Lights" },
{ id: 67, description: "דופן ימין של מוגבל בשל עבודתו מעל 50 מטר", image: "/images/image67.gif", type: "Lights" },
{ id: 68, description: "חרטום של שולת מוקשים מתחת ל-50 מטר (חסר אור בתמונה של משרד התחבורה)", image: "/images/image68.gif", type: "Lights" },
{ id: 69, description: "דופן ימין של ממוכן מעל 50 מטר", image: "/images/image69.gif", type: "Lights" },
{ id: 70, description: "כלי שייט המבצע עבודת צלילה - יש להתרחק מטר200", image: "/images/image70.gif", type: "Lights" },
{ id: 71, description: "כניסה למרינה באזור -IALAA", image: "/images/image71.gif", type: "Lights" },
{ id: 72, description: "דופן ימין של גורר בעל משך מעל 200 מטר וארכו מעל 50 מטרים ונגרר", image: "/images/image72.gif", type: "Lights" },
{ id: 73, description: "מכמורתן בדרך ואינו עושה דרכו", image: "/images/image73.gif", type: "Lights" },
{ id: 74, description: "כניסה למרינה באזור -IALAB", image: "/images/image74.gif", type: "Lights" },
{ id: 75, description: "כלי שייט מוגבל בשל השוקע", image: "/images/image75.gif", type: "Shapes" },
{ id: 76, description: "כלי שייט השולה מוקשים", image: "/images/image76.gif", type: "Shapes" },
{ id: 77, description: "כלי שייט עוגן", image: "/images/image77.gif", type: "Shapes" },
{ id: 78, description: "כלי שייט גורר עם משך מעל 200 מטר המוגבל בכושרו לתמרן", image: "/images/image78.gif", type: "Shapes" },
{ id: 79, description: "כלי שייט מוגבל בכושרו לתמרן", image: "/images/image79.gif", type: "Shapes" },
{ id: 80, description: "כלי שייט ללא שליטה", image: "/images/image80.gif", type: "Shapes" },
{ id: 81, description: "כלי שייט על שרטון", image: "/images/image81.gif", type: "Shapes" },
{ id: 82, description: "מפרשית המפעילה את מנועיה (ממוכן)", image: "/images/image82.gif", type: "Shapes" },
{ id: 83, description: "סימן מצוקה", image: "/images/image83.gif", type: "Shapes" },
{ id: 84, description: "כלי שייט המבצע דייג (דייג או מכמורתן)", image: "/images/image84.gif", type: "Shapes" },
{ id: 85, description: "סימון של רשת מעל 150 מטר הפרושה באחד מצדדיו של הדייג (ביחד עם תמונה 84)", image: "/images/image85.gif", type: "Shapes" },
{ id: 86, description: "גורר עם משך מעל 200 מטר (יהלום נוסף יוצג על הנגרר)", image: "/images/image86.gif", type: "Shapes" },
{ id: 87, description: "כלי שייט מוגבל בשל עבודתו המציין דופן בעלת מעבר חופשי ודופן אסורה למעבר", image: "/images/image87.gif", type: "Shapes" },
{ id: 88, description: "כלי שייט מוגבל בשל עבודתו המציין דופן בטוחה למעבר", image: "/images/image88.gif", type: "Shapes" },
{ id: 89, description: "כלי שייט המוגבל בשל עבודתו המציין דופן אסורה למעבר", image: "/images/image89.gif", type: "Shapes" },
{ id: 90, description: "כלי שייט המוגבל בשל עבודתו המציין דופן אסורה למעבר", image: "/images/image90.gif", type: "Shapes" },
{ id: 91, description: "דגל U", image: "/images/image91.gif", type: "Flags" },
{ id: 92, description: "דגל – לא (יחד עם דגל C משמש לסימן מצוקה)", image: "/images/image92.gif", type: "Flags" },
{ id: 93, description: "דגל C - כן (יחד עם דגל N משמש לסימן מצוקה)", image: "/images/image93.gif", type: "Flags" },
{ id: 94, description: "דגל T", image: "/images/image94.gif", type: "Flags" },
{ id: 95, description: "דגל B - פורק או טוען חומרים מסוכנים", image: "/images/image95.gif", type: "Flags" },
{ id: 96, description: "דגל S", image: "/images/image96.gif", type: "Flags" },
{ id: 97, description: "דגל G", image: "/images/image97.gif", type: "Flags" },
{ id: 98, description: "דגל - צוללים, יש להתרחק מטר200", image: "/images/image98.gif", type: "Flags" },
{ id: 99, description: "דגל K", image: "/images/image99.gif", type: "Flags" },
{ id: 100, description: "דגל H - נתב", image: "/images/image100.gif", type: "Flags" },
{ id: 101, description: "דגך L", image: "/images/image101.gif", type: "Flags" },
{ id: 102, description: "דגל D", image: "/images/image102.gif", type: "Flags" },
{ id: 103, description: "דגל I", image: "/images/image103.gif", type: "Flags" },
{ id: 104, description: "דגל - אדם בים", image: "/images/image104.gif", type: "Flags" },
{ id: 105, description: "דגל E", image: "/images/image105.gif", type: "Flags" },
{ id: 106, description: "דגל Q - ספינתי בריאה", image: "/images/image106.gif", type: "Flags" },
{ id: 107, description: "דגל X", image: "/images/image107.gif", type: "Flags" },
{ id: 108, description: "דגל P", image: "/images/image108.gif", type: "Flags" },
{ id: 109, description: "דגל F", image: "/images/image109.gif", type: "Flags" },
{ id: 110, description: "דגל V", image: "/images/image110.gif", type: "Flags" },
{ id: 111, description: "פונה ימינה", image: "/images/image111.gif", type: "Sounds" },
{ id: 112, description: "בראות טובה: לפני כניסה/יציאה מנמלמרינה /         בערפל: ממוכן עושה דרכו במים", image: "/images/image112.gif", type: "Sounds" },
{ id: 113, description: "משלב מנועי לאחור", image: "/images/image113.gif", type: "Sounds" },
{ id: 114, description: "פונה שמאלה", image: "/images/image114.gif", type: "Sounds" },
{ id: 115, description: "כוונותיך אינן ברורות (ניתן לצפור יותר מ-5 פעמים)", image: "/images/image115.gif", type: "Sounds" },
{ id: 116, description: "מבקש לעקוף אותך משמאל", image: "/images/image116.gif", type: "Sounds" },
{ id: 117, description: "מאשר עקיפה", image: "/images/image117.gif", type: "Sounds" },
{ id: 118, description: "בערפל: ממוכן בדרך שאינו עושה דרכו במים", image: "/images/image118.gif", type: "Sounds" },
{ id: 119, description: "סימן מצוקה (אות קולי ממשוך)", image: "/images/image119.gif", type: "Sounds" },
{ id: 120, description: "בערפל: כלי שייט נגרר", image: "/images/image120.gif", type: "Sounds" },
{ id: 121, description: "מבקש לעקוף אותך מימין", image: "/images/image121.gif", type: "Sounds" },
{ id: 122, description: "בערפל: גורר, מפרשית, דייג, מכמורתן, מוגבל בשל עבודתו, מוגבל בשל השוקע, שולת מוקשים וללא שליטה", image: "/images/image122.gif", type: "Sounds" },
{ id: 123, description: "אותות קוליים שאינם קיימים (מסיחים של משרד התחבורה)", image: "/images/image123.gif", type: "Sounds" },
{ id: 124, description: "אותות קוליים שאינם קיימים (מסיחים של משרד התחבורה)", image: "/images/image124.gif", type: "Sounds" },
{ id: 125, description: "אותות קוליים שאינם קיימים (מסיחים של משרד התחבורה)", image: "/images/image125.gif", type: "Sounds" },
{ id: 126, description: "אותות קוליים שאינם קיימים (מסיחים של משרד התחבורה)", image: "/images/image126.gif", type: "Sounds" },
{ id: 127, description: "ערוץ 6: בין ספינות", image: "/images/channel6.gif", type: "Comm Channels" },
{ id: 128, description: "ערוץ 8: בין ספינות", image: "/images/channel8.gif", type: "Comm Channels" },
{ id: 129, description: "ערוץ 11: חיל הים", image: "/images/channel11.gif", type: "Comm Channels" },
{ id: 130, description: "ערוץ 12: שרותי נמל", image: "/images/channel12.gif", type: "Comm Channels" },
{ id: 131, description: "ערוץ 13: בין ספינות", image: "/images/channel13.gif", type: "Comm Channels" },
{ id: 132, description: "ערוץ 14: שרותי נמל", image: "/images/channel14.gif", type: "Comm Channels" },
{ id: 133, description: "ערוץ 15: להגנה על 16 בתוך הספינה או לדינגי", image: "/images/channel15.gif", type: "Comm Channels" },
{ id: 134, description: "ערוץ 16: הקמת קשר והודעות מכל הסוגים", image: "/images/channel16.gif", type: "Comm Channels" },
{ id: 135, description: "ערוץ 17: להגנה על 16 בתוך הספינה או לדינגי", image: "/images/channel17.gif", type: "Comm Channels" },
{ id: 136, description: "ערוץ 20: שרותי נמל", image: "/images/channel20.gif", type: "Comm Channels" },
{ id: 137, description: "ערוץ 23: תחנת חוף", image: "/images/channel23.gif", type: "Comm Channels" },
{ id: 138, description: "ערוץ 24: תחנת חוף", image: "/images/channel24.gif", type: "Comm Channels" },
{ id: 139, description: "ערוץ 25: תחנת חוף", image: "/images/channel25.gif", type: "Comm Channels" },
{ id: 140, description: "ערוץ 26: תחנת חוף", image: "/images/channel26.gif", type: "Comm Channels" },
{ id: 141, description: "ערוץ 27: תחנת חוף", image: "/images/channel27.gif", type: "Comm Channels" },
{ id: 142, description: "ערוץ 28: תחנת חוף", image: "/images/channel28.gif", type: "Comm Channels" },
{ id: 143, description: "ערוץ 70: ערוץ דיגיטלי DSC", image: "/images/channel70.gif", type: "Comm Channels" },
{ id: 144, description: "ערוץ 75: להגנה על 16 השימוש אסור", image: "/images/channel75.gif", type: "Comm Channels" },
{ id: 145, description: "ערוץ 76: להגנה על 16 השימוש אסור", image: "/images/channel76.gif", type: "Comm Channels" },
];
